#!/bin/sh

# Bootstrap the repository.  Used when the repository is checked out from git.
# When using the source tarball, running this script is not necessary.

set -eu

if ! git --version >/dev/null; then
  echo "git not installed"
  exit 1
fi

git submodule update --init
git submodule update --recursive
git submodule sync

cp build-system/taler-build-scripts/configure ./configure || true
cp build-system/taler-build-scripts/conf/.style.yapf .style.yapf || true
