          <h3>11-2015: Christian Grothoff's explains the goals behind Taler</h3>
          <p>
           <video id="video" poster="/videos/inria2015interview.png" autobuffer="" height="180" width="320" controls="controls">
           <source src="/videos/inria2015interview.webm" type="video/webm">
           <source src="/videos/inria2015interview.ogv" type="video/ogv">
           </video>
          <a rel="license" href="https://creativecommons.org/licenses/by-nd/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="/images/ccby.png"></a><br>"<span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Taler</span>" by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Christian Grothoff, produced by Inria Rennes Bretagne Atlantique</span> is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-nd/3.0/deed.en_US">Creative Commons Attribution NoDerivatives 3.0 Unported License</a>.
          </p>
