          <h3>08-2017: We explain GNU Taler at SHA 2017</h3>
          <p>
           <video id="video" poster="/videos/sha2017taler.png" autobuffer="" height="360" width="640" controls="controls">
           <source src="/videos/sha2017taler.webm" type="video/webm">
           <source src="/videos/sha2017taler.ogv" type="video/ogv">
           <source src="/videos/sha2017taler.mp4" type="video/mp4">
           </video>
          </p>
          <p>
         <a rel="license" href="https://creativecommons.org/licenses/by-nd/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="{{ url('images/ccby.png')}}"></a><br>"<span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Taler</span>" by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Jeff Burdges, Christian Grothoff and Sereni-T, produced by c3voc.de</span> is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-nd/3.0/deed.en_US">Creative Commons Attribution NoDerivatives 3.0 Unported License</a>.
          </p>
