          <h3>02-2017: Florian Dold explains Taler at 50p in Bangalore</h3>
          <p>
           <video id="video" poster="/videos/dold50p.png" autobuffer="" height="360" width="640" controls="controls">
           <source src="/videos/dold50p.webm" type="video/webm">
           <source src="/videos/dold50p.ogv" type="video/ogv">
           </video>
          </p>
          <p>
          <a rel="license" href="https://creativecommons.org/licenses/by-nd/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="{{ url('images/ccby.png')}}"></a><br>"<span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Taler</span>" by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Florian Dold, produced by 50p</span> is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-nd/3.0/deed.en_US">Creative Commons Attribution NoDerivatives 3.0 Unported License</a>.
          </p>
