          <h3>04-2017: Sva explains GNU Taler at EasterHegg and Torsten demonstrates it is child's play</h3>
          <p>
           <iframe width="320" height="180" src="https://media.ccc.de/v/EH2017-8471-taler_-_talk/oembed" frameborder="0" allowfullscreen></iframe>
          <a rel="license" href="https://creativecommons.org/licenses/by-nd/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="/images/ccby.png"></a><br>"<span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Taler</span>" by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Sva, produced by c3voc.de</span> is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-nd/3.0/deed.en_US">Creative Commons Attribution NoDerivatives 3.0 Unported License</a>.
          </p>
