<article>
  <h3>
    <a name="gnunet-lsd001-p1">2019-10-04: GNS Technical Specification Milestone 1/4</a>
  </h3>
  <p>
    We are happy to announce the completion of the first milestone for the
    GNS Specification. The objective is to provide a detailed and comprehensive
    guide for implementors of the GNU Name System.
    The initial milestone consists of documenting the cryptographic principles
    of GNS data structures. This includes the specification of the GNS record
    wire and serialization formats as well as internationalization.<br/>
    <i>NOTE: The currently specified protocol is planned to be implemented for
    GNUnet 0.12. The current GNS implementation (0.11) exhibits minor but
    compatibility breaking deviations from this specification.</i>

    The draft specification <b>LSD001</b> can be found at:
    <ul>
      <li>Git: <a href="git://gnunet.org/lsd0001.git">LSD001</a></li>
      <li><a href="https://git.gnunet.org/lsd0001.git/tree/draft-schanzen-gns.txt">Link to TXT version</a></li>
      <li><a href="https://git.gnunet.org/lsd0001.git/tree/draft-schanzen-gns.html">Link to HTML version</a></li>
    </ul>

    The next milestone will bring the resolver logic specification.
  </p>
</article>
