<article>
  <h3><a name="">2019-06-28: Peer DSTJ is dead, long live peer Y924</a></h3>
  <p>
    After some issues with our infrastructure we needed to replace our bootstrapping peer. To avoid problems when connecting to GNUnet the operator of a peer needs to update its node by removing the peer ID <code>DSTJBRRKZ8TBW3FGK6B0M5QXWT9WYNZ45H5MCV4HY7ST64Q8T9F0</code> from the system. Here are two strategies to find copies of the respective file:
  </p>
  <p>
    <ol>
      <li><code>$ find / -name DSTJBRRKZ8TBW3FGK6B0M5QXWT9WYNZ45H5MCV4HY7ST64Q8T9F0</code></li>
      <li><code>$ locate DSTJBRRKZ8TBW3FGK6B0M5QXWT9WYNZ45H5MCV4HY7ST64Q8T9F0</code></li>
    </ol>
  </p>
</article>
