<article>
  <h3><a name="">2019-06-28: Peer DSTJ is dead, long live peer Y924</a></h3>
  <p>
    After some issues with our infrastructure we needed to replace our bootstrapping peer. To avoid problems when connecting to GNUnet the operator of a peer needs to update its node by removing the peer ID DSTJBRRKZ8TBW3FGK6B0M5QXWT9WYNZ45H5MCV4HY7ST64Q8T9F0 from the system.
    <!-- We should explain how to remove the peer ID. I am unsure how to do this correctly myself! -dvn -->
  </p>
</article>
