<article>
  <h3>2019-06-28: GNUnet Hacker Meeting 2019 at <a href="https://decentrale.ch">La Décentrale, Switzerland</a></h3>
  <p>
    The members of the GNUnet community met again in the wonderful souroundings of St. Imier to hack on GNUnet. New people joined our sessions until late at night. From bug squashing to digging our own dog food, from workshops to theoretical discussions of new services and usecases. And of course, pizza was in the game. 
  </p>
</article>

