<article>
  <h3><a name="">GNUnet Hacker Meeting 2019 at <a href="https://decentrale.ch">La Décentrale, Switzerland</a></h3>
  <p>
    The members of the GNUnet community met again in the wonderful souroundings of St. Imier to hack on the GNUnet. The people joined our sessions util deep night. From bug squashing to dog footing, from workshops to theoretical discussions of new services and usecases. And of course, pizza. 
  </p>
</article>

