<article>
  <h3>
    <a name="gnunet-icann-gns">2019-10-20: GNUnet project invited to ICANN66</a>
  </h3>
  <p>
    We are delighted to announce that ICANN has invited the GNUnet project to
    speak at the
    <a href="https://meetings.icann.org/en/montreal66">next ICANN Annual General Meeting</a>.
    We have been invited to join a panel discussion on <i>Emerging Internet Identifier Technologies</i>
    in order to share our ideas and work on the <i>GNU Name System (GNS)</i>.
    ICANN generously offered to cover travel and accomodation.
  </p>
  <p>
    The meeting will take place in Montreal between 2 - 7 November. The panel
    will tentatively be help on November 6th.
  </p>
  <p>
    <b>UPDATE:</b> The panel is on Tueday, November 5th 13:30 EDT with the possibility
    of remote participation: <a href="https://66.schedule.icann.org/meetings/1116895">Link</a>
  </p>
</article>
