<footer>
  <div class="container-fluid cushion-below">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-4">
          <ul class="footer-list">
            <li><p><a href="about.html">{{ _("About") }}</a></p></li>
            <li><p><a href="contact.html">{{ _("Contact") }}</a></p></li>
            <li><p><a href="ev.html">{{ _("GNUnet e.V.") }}</a></p></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4">
          <ul class="footer-list">
            <li><p><a href="https://bugs.gnunet.org/">{{ _("Bug Tracker") }}</a></p></li>
            <li><p><a href="discussion.html">{{ _("Discussion") }}</a></p></li>
            <li><p><a href="https://logs.gnunet.org/gnunet">{{ _("IRC logs") }}</a></p></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4">
          <ul class="footer-list">
            <li><p><a href="copyright.html">{{ _("Copyright Assignment") }}</a></p></li>
            <li><p><a href="https://ci.gnunet.org/">{{ _("Continuous Integration") }}</a></p></li>
            <li><p><a href="https://bibliography.gnunet.org/">{{ _("Bibliography") }}</a></p></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container text-center">
    <p>&copy; <a href="https://gnunet.org/ev">GNUnet e.V.</a></p> 2015, 2016, 2017, 2018</p>
    <p>{{ _("This page was created using <a href='https://www.gnu.org/'>Free Software</a> only.") }}</p>
  </div>
</footer>
