<footer>
  <div class="container-fluid cushion-below">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-4">
          <ul class="footer-list">
            <li><p><a href="about.html">About</a></p></li>
            <li><p><a href="investors.html">For Investors</a></p></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4">
          <ul class="footer-list">
            <li><p><a href="governments.html">Governments</a></p></li>
            <li><p><a href="merchants.html">Merchants</a></p></li>
            <li><p><a href="citizens.html">Citizens</a></p></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4">
          <ul class="footer-list">
            <li><p><a href="developers.html">Developer Resources</a></p></li>
            <li><p><a href="faq.html">FAQ</a></p></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container text-center">
    <p>&copy; <a href="https://gnunet.org/ev">GNUnet e.V.</a> and Inria 2015, 2016, 2017</p>
    <p>{{ _("This page was created using <a href='https://www.gnu.org/'>Free Software</a> only.") }}</p>
  </div>
</footer>
