       <div class="navbar navbar-default navbar-fixed-bottom" role="navigation">
         <div class="container lang-slector">
           <a href="#" onclick="setLang('en');"><img src="images/gb.png" alt="English"></img></a>
           <a href="#" onclick="setLang('de');"><img src="images/de.png" alt="Deutsch"></img></a>
           <a href="#" onclick="setLang('fr');"><img src="images/fr.png" alt="Fran&ccedil;ais"></img></a>
           <a href="#" onclick="setLang('it');"><img src="images/it.png" alt="Italiano"></img></a>
           <a href="#" onclick="setLang('es');"><img src="images/es.png" alt="Español"></img></a>
         </div>
       </div>
